### ISSUE TITLE
Xcode 12.5 warning

### ISSUE THREAD

**Issue by podkovyrin** [apple/swift-nio-zlib-support#4]
We're using swift-nio-zlib-support as a dependency of a Swift PM package we use. After updating to Xcode 14.5 (12E262) there's a warning:

```
Package Loading
ignoring declared target(s) 'swift-nio-zlib-support' in the system package
```

What does it mean in the first place? Is there any way to fix or suppress it? 
Thanks!

**Comment by Lukasa** [comment]
Good question. @tomerd any idea what SwiftPM change led to this warning?

For what it’s worth, swift-nio-zlib-support is no longer the most up-to-date way to depend on zlib. It may be worth considering adopting a newer package: we keep this one around to support old users of SwiftNIO, but we no longer use it ourselves.

**Comment by afern247** [comment]
Any updates? It's been months, or at least to suppress it

**Comment by Lukasa** [comment]
cc @tomerd

**Comment by tomerd** [comment]
I dont believe this is intentional, and I assume you see this also with SwiftPM CLI, not just Xcode, correct? If so, please file a bug with https://bugs.swift.org so that the SwiftPM team can track and address it

**Comment by tomerd** [comment]
regardless, @Lukasa point about swift-nio-zlib-support is no longer the most up-to-date way to depend on zlib is true and you should consider using more modern ways to depend on zlib. 

@Lukasa should you add some of this information to the project's README?

**Comment by Lukasa** [comment]
@tomerd see #5.
