### ISSUE TITLE
Zlib as systemLibrary

### ISSUE THREAD

**Issue by emarashliev** [apple/swift-nio-zlib-support#6]
Can someone help me to figure out how excaly to add zlib as systemLibrary or as linkerSettings in my Package.swift 
I'm trying to add it like that 
```
let package = Package(
    name: "MyLib",
    platforms: [
        .iOS(.v13),
    ],
    products: [
        .library(
            name: "MyLib",
            targets: ["MyLib"]),
    ],
    targets: [
        .target(
            name: "MyLib",
            dependencies: ["zlib"]),
     
        .systemLibrary(name: "zlib"),

)
```
But I'm getting 
`Source files for target zlib should be located under 'Sources/zlib', or a custom sources path can be set with the 'path' property in Package.swift`

**Comment by glbrntt** [comment]
SwiftNIO Extras does this by having an additional target ("CNIOExtrasZlib") which links zlib and provides namespaced wrappers around it (see: https://github.com/apple/swift-nio-extras/blob/main/Sources/CNIOExtrasZlib/include/CNIOExtrasZlib.h). 

The linker setting required for the target is `.linkedLibrary("z")` (not "zlib").

The relevant parts of Package.swift are:
- https://github.com/apple/swift-nio-extras/blob/a75e92bde3683241c15df3dd905b7a6dcac4d551/Package.swift#L79-L84
- https://github.com/apple/swift-nio-extras/blob/a75e92bde3683241c15df3dd905b7a6dcac4d551/Package.swift#L25-L32

**Comment by emarashliev** [comment]
@glbrntt  Thank you so very much! 🙏
